runtime: go111
service: default
instance_class: F1
# basic_scaling:
#   max_instances: 2
#   idle_timeout: 3m

includes:
- secret.yaml

handlers:
- url: /task/.*
  script: auto
  login: admin
  secure: always

- url: .*
  script: auto
  secure: always

